DATA:
  benchmark: 'crackls315' # benchmark name, choices ['drive', 'cracktree200', 'crack500', 'roads]
  datapath: datasets/crackls315
  classes: 1

MODEL:
  architecture: 'cadet'
  backbone: 'resbase32'
  steps: 2
  use_gau: [True, True, True, True, True]
  use_fim: [True, True, True, True]
  up: [True, True, True, True]
  reduce_dim: False
  # 跳连线上的模块设定
  module: ['GAU', 'GAU', 'GAU', 'GAU', 'GAU']
  sat_pos: [360, 180, 90, 45, 22]
  use_fusion: True
  dual_decoder: True
  dual_module: ['GAU', 'GAU', 'GAU', 'SAT', 'SAT']


TRAIN:
  logname: cadet_crackls315_train_dual_SAT_FFD_sigmoid_bs4 #save log and model
  train_gpu: [0]
  start_epoch: 0
  epochs: 2000
  img_mode: crop
  img_size: 360
  nworker: 8
  batch_size: 4  # batch size for trainin
  batch_size_val: 1
  evaluate: True
  resume: False # path to latest checkpoint (default: False), set the path for True
  optimizer: 'Adam'
  base_lr: 0.001
  lr_update: True
  lr_step: 10000
  ignore_label: 255
  weight_decay: 0.0005
  gamma: 0.95
  weight:
